# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [6]:
import numpy as np
import random
import scipy.stats as sps
import cv2


ModuleNotFoundError: No module named 'scipy'

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [7]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.8239794  0.67129882 0.26702543 ... 0.72782834 0.55282148 0.38459964]
 [0.56560029 0.12233135 0.20256998 ... 0.12603872 0.99634733 0.53760634]
 [0.10647411 0.89008365 0.51341929 ... 0.15654906 0.27999015 0.89380222]
 ...
 [0.47563425 0.96308113 0.72417558 ... 0.82357431 0.25787398 0.80961819]
 [0.25642347 0.16858367 0.72172176 ... 0.0980568  0.6545032  0.94943244]
 [0.33584315 0.73479656 0.19517179 ... 0.91302848 0.27516878 0.27528103]]
[[0.50415903 0.04156635 0.14430808 ... 0.33009786 0.595984   0.54612283]
 [0.57203412 0.68377403 0.31500083 ... 0.1108941  0.61301952 0.78703947]
 [0.21348638 0.73912913 0.89192929 ... 0.43593244 0.55388882 0.09885895]
 ...
 [0.90539137 0.87571193 0.15195246 ... 0.81736041 0.05713931 0.07516051]
 [0.18561887 0.5288915  0.70647271 ... 0.03548089 0.73094719 0.51603731]
 [0.3948235  0.14286133 0.05746082 ... 0.82104887 0.94790689 0.10008876]]


Без использования numpy

In [8]:
a = [[1, 2], [3, 4]]#для проверки
b = [[5, 6], [7, 8]]#для проверки

def mult(a, b):
    result = [[0 for j in range(len(b[0]))] for i in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

result = mult(a, b)
print(result)

[[19, 22], [43, 50]]


C использованием numpy

In [9]:
import numpy as np

def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [10]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [11]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 0 ns


In [12]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [13]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.52003124 0.47771117 0.25381781] [0.73719867 0.86542318 0.93777681]


In [14]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i]*b[i]
    return s


In [15]:
import numpy as np
def np_scalar_product(a, b):
    s = np.dot(a, b)
    return s

In [16]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** ________________________________NumPy оказывается эффективнее, потому что библиотека NumPy содержит оптимизированные функции для работы с массивами и матрицами. Т.к. он написан на C в нем используют оптимизированные алгоритмы.  Скорость вычислений в NumPy зависит от размера массивов , а также от сложности операций, выполняемых с ними.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [17]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag = np.diag(a)
  even_diag = diag[diag % 2 == 0]
  if len(even_diag) == 0:
    return 0
  else:
    return np.sum(even_diag)

In [18]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 8, 6, 3, 9],
       [7, 9, 7, 1, 8],
       [9, 6, 5, 8, 8],
       [6, 5, 4, 7, 9],
       [4, 4, 9, 7, 8]])

In [19]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


8

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [20]:
# функция, решающая задачу с помощью NumPy
import numpy as np
import scipy.stats as sps

def np_sec_av(A):
    return np.mean(A**2)

ModuleNotFoundError: No module named 'scipy'

In [21]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

NameError: name 'sps' is not defined

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [22]:
# функция, решающая задачу с помощью NumPy
import numpy as np

def np_encode(a):
    x = np.array([k for k, g in groupby(a)])
    num = np.array([len(list(g)) for k, g in groupby(a)])
    return x, num

In [23]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: total: 0 ns
Wall time: 0 ns


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [24]:
# функция, решающая задачу с помощью NumPy
from copy import copy
import numpy as np

def np_transformation(X, a=1):
    new_X = X.copy()
    new_X[1::2] = a
    new_X[::2] **= 3
    new_X = new_X[::-1]
    result = np.concatenate((X, new_X))
    return result[::-1]

In [25]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: total: 0 ns
Wall time: 0 ns
