In [30]:
import numpy as np
import random
import scipy.stats as sps
import cv2

**Задание 1**
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [31]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.70882733 0.77628961 0.6044355  ... 0.32898093 0.56675663 0.06221244]
 [0.95244796 0.81875788 0.91824693 ... 0.61228759 0.36726679 0.30612842]
 [0.02135128 0.4465084  0.99040897 ... 0.50743157 0.00842061 0.8238916 ]
 ...
 [0.43652905 0.09037112 0.02016452 ... 0.58778226 0.07744401 0.81621401]
 [0.8369724  0.17361809 0.71739276 ... 0.5228259  0.21706565 0.91845031]
 [0.49081988 0.55440531 0.28891238 ... 0.03308672 0.80958769 0.88622908]]
[[0.86111124 0.28056365 0.713439   ... 0.25948412 0.47805225 0.92166154]
 [0.92126026 0.90423652 0.63318929 ... 0.07050148 0.58915451 0.88452115]
 [0.53075449 0.88744594 0.15443415 ... 0.62100615 0.57070483 0.31993861]
 ...
 [0.90094839 0.89664341 0.59366533 ... 0.10314615 0.09184422 0.04877345]
 [0.86491308 0.64478167 0.8019909  ... 0.5993342  0.0596516  0.03562241]
 [0.11983784 0.99867504 0.85255001 ... 0.12420517 0.41495192 0.49624629]]


без использования numpy

In [32]:
a = [[1, 2], [3, 4]]#для проверки
b = [[5, 6], [7, 8]]#для проверки

def mult(a, b):
    result = [[0 for j in range(len(b[0]))] for i in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

result = mult(a, b)
print(result)

[[19, 22], [43, 50]]


C использованием numpy

In [33]:
import numpy as np

def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [34]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)


CPU times: user 16 µs, sys: 3 µs, total: 19 µs
Wall time: 23.4 µs


In [35]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 56 µs, sys: 10 µs, total: 66 µs
Wall time: 71.3 µs


In [36]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0

**Задание 2**
Вам подаются на вход два вектора a и b в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy и без. Засеките время работы, как это показано в заданиях выше.

In [37]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.01579869 0.80652373 0.3318184 ] [0.74287064 0.33224658 0.18148134]


In [38]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i]*b[i]
    return s

In [39]:
import numpy as np
def np_scalar_product(a, b):
    s = np.dot(a, b)
    return s

In [40]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 14 µs, sys: 3 µs, total: 17 µs
Wall time: 19.3 µs
CPU times: user 38 µs, sys: 7 µs, total: 45 µs
Wall time: 47.4 µs


0.0

**Почему методы numpy оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?**

Ответ: ____NumPy оказывается эффективнее, потому что библиотека NumPy содержит оптимизированные функции для работы с массивами и матрицами. Т.к. он написан на C в нем используют оптимизированные алгоритмы. Скорость вычислений в NumPy зависит от размера массивов , а также от сложности операций, выполняемых с ними.

**Задание 3.** Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести 0.

In [21]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag = np.diag(a)
  even_diag = diag[diag % 2 == 0]
  if len(even_diag) == 0:
    return 0
  else:
    return np.sum(even_diag)

In [22]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 4, 1, 6, 8],
       [4, 5, 3, 7, 1],
       [7, 9, 3, 5, 2],
       [4, 8, 6, 1, 5],
       [7, 6, 6, 2, 3]])

In [23]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 91 µs, sys: 17 µs, total: 108 µs
Wall time: 115 µs


0

**Задание 4**. На вход дан двумерный массив  X . Напишите функцию, которая для каждой строчки  x=(x1,x2,…,xn)  массива  X  строит строчку  s=(s1,s2,…,sn) , где  sk=(x1+...+xk)/k , а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и  X .

In [24]:
# функция, решающая задачу с помощью NumPy
import numpy as np
import scipy.stats as sps

def np_sec_av(A):
    return np.mean(A**2)

In [25]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[6.70139822e-01 8.01829409e-01 9.71175619e-01 2.92555168e-01
 4.17009652e-01 1.17392169e-01 6.31364013e-01 6.05483584e-01
 5.64506257e-01 8.29922681e-01 8.38150832e-01 3.77614407e-01
 1.02027361e-01 3.66102799e-02 8.37525678e-01 6.55909398e-01
 8.34946107e-01 3.31885005e-01 3.43529971e-01 5.28466330e-01
 9.88176134e-01 6.14461734e-01 2.15362017e-01 8.11539039e-01
 9.44677743e-01 7.23792354e-01 6.17472871e-01 1.65668101e-01
 4.83625025e-01 7.00222396e-01 4.65507747e-02 5.41063680e-01
 8.69536548e-01 9.17409831e-01 8.75015697e-01 9.63039943e-01
 3.97334921e-01 1.42242121e-01 9.90621815e-01 6.27937659e-01
 9.06259854e-01 4.29122145e-01 2.61328027e-01 4.52729023e-01
 3.06803179e-01 2.16864707e-01 1.72169384e-01 5.70826777e-01
 7.37033654e-01 8.46182585e-01 8.75238291e-01 3.78457714e-01
 9.17206828e-01 2.35637770e-01 4.59274793e-01 2.83533559e-01
 7.61151574e-01 1.93870731e-01 6.07999440e-01 6.40834519e-02
 9.49005382e-01 1.13617386e-02 5.30721253e-01 5.88331179e-01
 4.21896956e-01 6.430621

**Задание 5**.Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [26]:
# функция, решающая задачу с помощью NumPy
import numpy as np

def np_encode(a):
    x = np.array([k for k, g in groupby(a)])
    num = np.array([len(list(g)) for k, g in groupby(a)])
    return x, num

In [27]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 46 µs, sys: 9 µs, total: 55 µs
Wall time: 59.8 µs


**Задание 6**. Пусть задан некоторый одномерный массив  X . Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число  a  (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив  X  при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.

Пример:
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [28]:
# функция, решающая задачу с помощью NumPy
from copy import copy
import numpy as np

def np_transformation(X, a=1):
    new_X = X.copy()
    new_X[1::2] = a
    new_X[::2] **= 3
    new_X = new_X[::-1]
    result = np.concatenate((X, new_X))
    return result[::-1]

In [29]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 86 µs, sys: 15 µs, total: 101 µs
Wall time: 107 µs
